%NAME%
linux-lts

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL_GIT%
true

%KERNEL-SOURCE%
git clone --depth=1 -b linux-rolling-lts https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git linux

%IGNORE-KERNEL-SOURCE%
false

%CONFIG%
defconfig

%MAKEOPTS%
-j$(nproc)

%BUILD%
make

%INSTALL-MODULES%
true

%INSTALL%
make install
