%patched/zen/zen-latest.conf%
VERSION=latest
NAME=linux-zen
TAGS=[zen]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%vanilla/latest/vanilla-latest.conf%
VERSION=latest
NAME=vanilla
TAGS=[latest]
CATEGORIES=[vanilla]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true
