%patched/zen/zen-latest.conf%
VERSION=latest
NAME=linux-zen
TAGS=[zen]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%vanilla/latest/vanilla-latest.conf%
VERSION=latest
NAME=linux
TAGS=[latest]
CATEGORIES=[vanilla]
EXTERNAL_SOURCES=false
IGNORE_KERNEL_SOURCE=false

%vanilla/lts/lts-latest.conf%
VERSION=latest
NAME=linux-lts
TAGS=[lts]
CATEGORIES=[vanilla]
EXTERNAL_SOURCES=false
IGNORE_KERNEL_SOURCE=false

%patched/cachyos/cachyos-latest.conf%
VERSION=latest
NAME=linux-cachyos
TAGS=[cachyos,performance]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%patched/xanmod/xanmod-latest.conf%
VERSION=latest
NAME=linux-xanmod
TAGS=[xanmod,performance]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%patched/libre/libre-latest.conf%
VERSION=latest
NAME=linux-libre
TAGS=[libre,freedom]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%patched/hardened/hardened-latest.conf%
VERSION=latest
NAME=linux-hardened
TAGS=[hardened,security]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%patched/rt/rt-latest.conf%
VERSION=latest
NAME=linux-rt
TAGS=[rt,realtime]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%patched/tkg/tkg-latest.conf%
VERSION=latest
NAME=linux-tkg
TAGS=[tkg,gaming,custom]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true

%patched/bore/bore-latest.conf%
VERSION=latest
NAME=linux-bore
TAGS=[bore,scheduler]
CATEGORIES=[patched]
EXTERNAL_SOURCES=true
IGNORE_KERNEL_SOURCE=true
