%NAME%
linux-zen

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/kernel-experimental/kernels/patched/zen/zen-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x zen-latest.sh
./zen-latest.sh start

%PATCH%

%BUILD%
./zen-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./zen-latest.sh install
