%NAME%
linux-tkg

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/tkg/tkg-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x tkg-latest.sh
./tkg-latest.sh start

%PATCH%

%BUILD%
./tkg-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./tkg-latest.sh install
