%NAME%
vanilla

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/vanilla/latest/vanilla-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x vanilla-latest.sh
./vanilla-latest.sh start

%PATCH%

%BUILD%
./vanilla-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./vanilla-latest.sh install
