%NAME%
vanilla-latest

%VERSION%
latest

%SOURCE-DIR%
linux-{VERSION}

%KERNEL-SOURCE%
https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-{VERSION}.tar.xz

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/vanilla/latest/vanilla-latest.sh

%CONFIG%
dihconfig

%MAKEOPTS%
V=1

%PREPARE%
chmod +x vanilla-latest.sh
sh vanilla-latest.sh

%PATCH%

%BUILD%
echo "test working"

%INSTALL-MODULES%
false

%INSTALL%
echo "we made it"
