%NAME%
linux-xanmod

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/xanmod/xanmod-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x xanmod-latest.sh
./xanmod-latest.sh start

%PATCH%

%BUILD%
./xanmod-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./xanmod-latest.sh install
