%NAME%
linux-libre

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/libre/libre-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x libre-latest.sh
./libre-latest.sh start

%PATCH%

%BUILD%
./libre-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./libre-latest.sh install
