[recipe]
interpreter = "sh"

[[step]]
run = "sed -ri \"s:.*(AUX_MODULES.*valid):\\1:\" modules.cfg"

[[step]]
run = "sed -r \"s:.*(#.*SUBPIXEL_RENDERING) .*:\\1:\" -i include/freetype/config/ftoption.h"

[[step]]
run = "./configure --prefix=/usr --disable-static --enable-freetype-config --with-harfbuzz=dynamic"

[[step]]
run = "make -j$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1024 / 1024 / 2 ))"

[[step]]
run = "sudo make install || doas make install"
