%NAME%
linux-cachyos

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/cachyos/cachyos-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x cachyos-latest.sh
./cachyos-latest.sh start

%PATCH%

%BUILD%
./cachyos-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./cachyos-latest.sh install
