%NAME%
linux-rt

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/rt/rt-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x rt-latest.sh
./rt-latest.sh start

%PATCH%

%BUILD%
./rt-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./rt-latest.sh install
