%NAME%
linux-bore

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/bore/bore-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x bore-latest.sh
./bore-latest.sh start

%PATCH%

%BUILD%
./bore-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./bore-latest.sh install
