%NAME%
linux-hardened

%VERSION%
latest

%SOURCE-DIR%
linux

%KERNEL-SOURCE%

%IGNORE-KERNEL-SOURCE%
true

%EXTERNAL-SOURCES%
https://raw.githubusercontent.com/HuntedByTheIRS/iota-packages-staging/refs/heads/main/kernels/patched/hardened/hardened-latest.sh

%CONFIG%

%MAKEOPTS%

%PREPARE%
chmod +x hardened-latest.sh
./hardened-latest.sh start

%PATCH%

%BUILD%
./hardened-latest.sh build

%INSTALL-MODULES%
false

%INSTALL%
./hardened-latest.sh install
